# refer https://gohugo.io/getting-started/configuration/

baseUrl: /
title: "MyController.org: The OpenSource Controller"
enableRobotsTXT: true
theme: ["docsy"]
enableGitInfo: true
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
disableKinds: ["taxonomy", "taxonomyTerm"]
pygmentsCodeFences: true
pygmentsUseClasses: false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic: false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle: "tango"
enableEmoji: true

permalinks:
  blog: "/:section/:year/:month/:day/:slug/"

blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
  angledQuotes: false
  latexDashes: true

imaging:
  resampleFilter: "CatmullRom"
  quality: 75
  anchor: "smart"

services:
  googleAnalytics:
    id: "UA-196420928-1"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango # https://xyproto.github.io/splash/docs/all.html

languages:
  en:
    title: "MyController.org: The OpenSource Controller"
    description: "The OpenSource Controller"
    languageName: "English"
    # Weight used for sorting.
    weight: 1
    menu:
      main:
      - name: "MyController 1.x"
        url: "https://v1.mycontroller.org"
        weight: -10
  
      - name: "Forum"
        pre: "<i class='fa fa-comments fa-lg'></i>"
        url: "https://forum.mycontroller.org"
        weight: -9 
  
      - name: "GitHub"
        identifier: "github"
        pre: "<i class='fab fa-github fa-lg'></i>"
        url: "https://github.com/mycontroller-org/backend"
        weight: -8

  ta:
    title: "MyController.org: The OpenSource Controller"
    description: "The OpenSource Controller"
    languageName: தமிழ்
    contentDir: "content/ta"
    #time_format_default: "01.02.2006"
    #time_format_blog: "01.02.2006"
    menu:
      main:
      - name: "MyController 1.x"
        url: "https://v1.mycontroller.org"
        weight: -10
  
      - name: மன்றம்
        pre: "<i class='fa fa-comments fa-lg'></i>"
        url: "https://forum.mycontroller.org"
        weight: -9 
  
      - name: "GitHub"
        identifier: "github"
        pre: "<i class='fab fa-github fa-lg'></i>"
        url: "https://github.com/mycontroller-org/server"
        weight: -8

outputs:
  section: ["HTML", "print"]

params:
  pageVariables:
    version: 2.0.0-devel

  copyright: "The MyController.org Authors."
  # privacy_policy: "https://policies.google.com/privacy"

  # First one is picked as the Twitter card image if not set on page.
  # images: ["images/project-illustration.png"]

  # Repository configuration (URLs for in-page links to opening issues and suggesting changes)
  github_repo: "https://github.com/mycontroller-org/documentation"
  # An optional link to a related project repo. For example, the sibling repository where your product code lives.
  github_project_repo: "https://github.com/mycontroller-org"

  # Specify a value here if your content directory is not in your repo's root directory
  # github_subdir: ""

  # Uncomment this if you have a newer GitHub repo with "main" as the default branch,
  # or specify a new value if you want to reference another branch in your GitHub links
  # github_branch: "main"

  # Google Custom Search Engine ID. Remove or comment out to disable search.
  # gcs_engine_id: "d72aa9b2712488cc3"

  # Enable Algolia DocSearch
  algolia_docsearch: false

  # Enable Lunr.js offline search
  offlineSearch: true

  # Enable syntax highlighting and copy buttons on code blocks with Prism
  prism_syntax_highlighting: true

  # User interface configuration
  ui:
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact: false
    #  Set to true to disable breadcrumb navigation.
    breadcrumb_disable: false
    #  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable: true
    #  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
    navbar_logo: true
    # Set to true to disable the About link in the site footer
    footer_about_disable: true

    # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
    # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
    # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
    # add "hide_feedback: true" to the page's front matter.
    feedback:
      enable: false
      # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
      yes: 'Thanks for your feedback!'
      no: 'Sorry to hear that. Please <a href="https://github.com/mycontroller-org/documentation/issues/new">tell us how we can improve</a>.'

    # Adds a reading time to the top of each doc.
    # If you want this feature, but occasionally need to remove the Reading time from a single page, 
    # add "hide_readingtime: true" to the page's front matter
    readingtime:
      enable: true

  links:
    # End user relevant links. These will show up on left side of footer and in the community page if you have one.
    user:
      - name: "Twitter"
        url: "https://twitter.com/mycontrollerorg"
        icon: "fab fa-twitter"
        desc: "Follow us on Twitter to get the latest news!"

    # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
    developer:
      - name: "GitHub"
        url: "https://github.com/mycontroller-org"
        icon: "fab fa-github"
        desc: "Development takes place here!"
